### ISSUE TITLE
State of the OpenCL pipeline

### ISSUE THREAD

**Issue by rok-cesnovar** [bstatcomp/math#11]
In this issue we will try to keep track of what me, Steve, Tadej and Davor are working on regarding OpenCL support in Stan Math. 

I think it would be good to cross post this on Discourse from time to time. Once this OpenCL stuff picks up, hopefully other people will join in.

**In review:**
- basic kernel generator (Tadej)
- add a var and vari template to matrix_cl (Steve)

**Stuff in the works but not ready for review** 
- make /opencl/rev and move rev OpenCL code there
- QR decomposition (Tadej)
- eigendecomposition (Tadej)
- generate simple kernels using kernel generators (Tadej)
- use enums in OpenCL kernels (?)

**Idea list:** 
- OpenCL 2.0 & shared virtual memory
- explore enqueueMapBuffer and pinned memory
- expression templates
- list of possible functions to parallelize (not prioritized) 
[TODO.txt](https://github.com/bstatcomp/math/files/3486096/TODO.txt)

**Comment by seantalts** [comment]
Thanks for writing this up! Is anything waiting on review or input from me?

**Comment by rok-cesnovar** [comment]
The triangular multiply PR is ready for review. It adds a new kernel but its actually a copy of the regular matrix multiply kernel with a few minor optimizations.
