### ISSUE TITLE
Readme.md improvements

### ISSUE THREAD

**Issue by demsarjure** [bstatcomp/math#5]
#### Summary:
There is an error/typo in the Readme.md file, also instructions for installation on Windows would be probably easier to execute if a link to clinfo binaries would be provided instead of a link to clinfo github repository, which requires its own compilation, that is also not straightforward.

#### Description:
**1. Typo**
Readme.md for OpenCL GPU support has a typo. Under the section Integration with cmdstan, the commands for testing the GP3 example are:

- Linux and MacOS: make examples/CP/cp3
- Windows: make examples/CP/cp3.exe

but they should be:

- Linux and MacOS: make examples/GP/gp3
- Windows: make examples/GP/gp3.exe

**2. clinfo binaries** 
Under installation guidelines for Windows there is a link to github repository of clinfo. Instead I would provide links to 32-bit clinfo.exe (https://ci.appveyor.com/api/projects/oblomov/clinfo/artifacts/clinfo.exe?job=platform%3a+x86), and 64-bit exe (https://ci.appveyor.com/api/projects/oblomov/clinfo/artifacts/clinfo.exe?job=platform%3a+x64).

#### Reproducible Steps:
/

#### Current Output:
/

#### Expected Output:
/

#### Additional Information:
/

#### Current Version:
v2.17.0

**Comment by davors** [comment]
Thanks for noticing. I corrected the typo and changed the link to the binary of clinfo for windows OS. The 32-bit clinfo is not needed since, cmdstan/stan math does not support 32-bit compilers.
