### ISSUE TITLE
OpenCL installation instructions: cmdstan should be CmdStan

### ISSUE THREAD

**Issue by demsarjure** [bstatcomp/math#6]
#### Summary:
When Stan guys refer to CmdStan they use "CmdStan" not cmdstan. This issue is only there in "Integration with cmdstan" section.

#### Description:
/

#### Reproducible Steps:
/

#### Current Output:
/

#### Expected Output:
/

#### Additional Information:
/

#### Current Version:
v2.17.0

**Comment by rok-cesnovar** [comment]
Fixed
